//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Messages.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Messages.Enums.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change type.
        /// </summary>
        public static string ActionLog_ChangeType {
            get {
                return ResourceManager.GetString("ActionLog_ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ActionLog_Delete {
            get {
                return ResourceManager.GetString("ActionLog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string ActionLog_DeleteImage {
            get {
                return ResourceManager.GetString("ActionLog_DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string ActionLog_Insert {
            get {
                return ResourceManager.GetString("ActionLog_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        public static string ActionLog_InsertImage {
            get {
                return ResourceManager.GetString("ActionLog_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ActionLog_Update {
            get {
                return ResourceManager.GetString("ActionLog_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage App Settings.
        /// </summary>
        public static string Appsettings {
            get {
                return ResourceManager.GetString("Appsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company info.
        /// </summary>
        public static string AppSettingType_CompanyInfo {
            get {
                return ResourceManager.GetString("AppSettingType_CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Formats.
        /// </summary>
        public static string AppSettingType_DateFormats {
            get {
                return ResourceManager.GetString("AppSettingType_DateFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time Formats.
        /// </summary>
        public static string AppSettingType_DateTimeFormats {
            get {
                return ResourceManager.GetString("AppSettingType_DateTimeFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        public static string AppSettingType_Domains {
            get {
                return ResourceManager.GetString("AppSettingType_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string AppSettingType_EmailSettings {
            get {
                return ResourceManager.GetString("AppSettingType_EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend Color.
        /// </summary>
        public static string AppSettingType_FrontEndColor {
            get {
                return ResourceManager.GetString("AppSettingType_FrontEndColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map Settings.
        /// </summary>
        public static string AppSettingType_GoogleMapSettings {
            get {
                return ResourceManager.GetString("AppSettingType_GoogleMapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Data.
        /// </summary>
        public static string AppSettingType_SiteData {
            get {
                return ResourceManager.GetString("AppSettingType_SiteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Style Settings.
        /// </summary>
        public static string AppSettingType_SiteStyleSettings {
            get {
                return ResourceManager.GetString("AppSettingType_SiteStyleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Vendor Setting.
        /// </summary>
        public static string AppSettingType_SmsVendorSetting {
            get {
                return ResourceManager.GetString("AppSettingType_SmsVendorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Server Info.
        /// </summary>
        public static string AppSettingType_Smtp {
            get {
                return ResourceManager.GetString("AppSettingType_Smtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        public static string AppSettingType_State {
            get {
                return ResourceManager.GetString("AppSettingType_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Transfer Settings.
        /// </summary>
        public static string AppSettingType_SystemTransferSettings {
            get {
                return ResourceManager.GetString("AppSettingType_SystemTransferSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string ArticeStatus_Hidden {
            get {
                return ResourceManager.GetString("ArticeStatus_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string ArticeStatus_Visible {
            get {
                return ResourceManager.GetString("ArticeStatus_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Backend Users.
        /// </summary>
        public static string BackendUsers {
            get {
                return ResourceManager.GetString("BackendUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age setting.
        /// </summary>
        public static string BePage_AgeSetting {
            get {
                return ResourceManager.GetString("BePage_AgeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string BePage_Customer {
            get {
                return ResourceManager.GetString("BePage_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer log.
        /// </summary>
        public static string BePage_CustomerLog {
            get {
                return ResourceManager.GetString("BePage_CustomerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string BePage_Files {
            get {
                return ResourceManager.GetString("BePage_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose mail.
        /// </summary>
        public static string BePage_GuiMail {
            get {
                return ResourceManager.GetString("BePage_GuiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead time setting.
        /// </summary>
        public static string BePage_LeadTimeSetting {
            get {
                return ResourceManager.GetString("BePage_LeadTimeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo image.
        /// </summary>
        public static string BePage_Logo {
            get {
                return ResourceManager.GetString("BePage_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message on site setup.
        /// </summary>
        public static string BePage_MessageSetup {
            get {
                return ResourceManager.GetString("BePage_MessageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string BePage_News {
            get {
                return ResourceManager.GetString("BePage_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string BePage_NhomSanPham {
            get {
                return ResourceManager.GetString("BePage_NhomSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of chair setting.
        /// </summary>
        public static string BePage_NumberOfChairSetting {
            get {
                return ResourceManager.GetString("BePage_NumberOfChairSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dentist setting.
        /// </summary>
        public static string BePage_NumberOfDoctorSetting {
            get {
                return ResourceManager.GetString("BePage_NumberOfDoctorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of staff setting.
        /// </summary>
        public static string BePage_NumberOfStaffSetting {
            get {
                return ResourceManager.GetString("BePage_NumberOfStaffSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff position setting.
        /// </summary>
        public static string BePage_PositionSetting {
            get {
                return ResourceManager.GetString("BePage_PositionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential customer.
        /// </summary>
        public static string BePage_PotentialCustomer {
            get {
                return ResourceManager.GetString("BePage_PotentialCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospects customer.
        /// </summary>
        public static string BePage_ProspectsCustomer {
            get {
                return ResourceManager.GetString("BePage_ProspectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product page.
        /// </summary>
        public static string BePage_SanPham {
            get {
                return ResourceManager.GetString("BePage_SanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization setting.
        /// </summary>
        public static string BePage_SpecializationSetting {
            get {
                return ResourceManager.GetString("BePage_SpecializationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Message.
        /// </summary>
        public static string BePage_TinDang {
            get {
                return ResourceManager.GetString("BePage_TinDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string BePage_UOM {
            get {
                return ResourceManager.GetString("BePage_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using RC setting.
        /// </summary>
        public static string BePage_UsingRCSetting {
            get {
                return ResourceManager.GetString("BePage_UsingRCSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string BeUserStatus_Active {
            get {
                return ResourceManager.GetString("BeUserStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string BeUserStatus_Locked {
            get {
                return ResourceManager.GetString("BeUserStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNY.
        /// </summary>
        public static string Currency_CNY {
            get {
                return ResourceManager.GetString("Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Rial.
        /// </summary>
        public static string Currency_IRR {
            get {
                return ResourceManager.GetString("Currency_IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia Riel.
        /// </summary>
        public static string Currency_KHR {
            get {
                return ResourceManager.GetString("Currency_KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laos Kip.
        /// </summary>
        public static string Currency_LAK {
            get {
                return ResourceManager.GetString("Currency_LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND.
        /// </summary>
        public static string Currency_VND {
            get {
                return ResourceManager.GetString("Currency_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CustomerType_Current {
            get {
                return ResourceManager.GetString("CustomerType_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential.
        /// </summary>
        public static string CustomerType_Potential {
            get {
                return ResourceManager.GetString("CustomerType_Potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospects.
        /// </summary>
        public static string CustomerType_Prospects {
            get {
                return ResourceManager.GetString("CustomerType_Prospects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Nam {
            get {
                return ResourceManager.GetString("Gender_Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Nu {
            get {
                return ResourceManager.GetString("Gender_Nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string HtmlContentDisplayType_Email {
            get {
                return ResourceManager.GetString("HtmlContentDisplayType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string HtmlContentDisplayType_SMS {
            get {
                return ResourceManager.GetString("HtmlContentDisplayType_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Network.
        /// </summary>
        public static string HtmlContentDisplayType_WebSite {
            get {
                return ResourceManager.GetString("HtmlContentDisplayType_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        public static string MaritalStatus_Divorced {
            get {
                return ResourceManager.GetString("MaritalStatus_Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string MaritalStatus_Married {
            get {
                return ResourceManager.GetString("MaritalStatus_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string MaritalStatus_Single {
            get {
                return ResourceManager.GetString("MaritalStatus_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to user - order success.
        /// </summary>
        public static string MessageCase_DatHangThanhCong {
            get {
                return ResourceManager.GetString("MessageCase_DatHangThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to user - an email has been sent to you for confirm external id.
        /// </summary>
        public static string MessageCase_ExternalLoginIdConfirm {
            get {
                return ResourceManager.GetString("MessageCase_ExternalLoginIdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to user - Forgot password email sent.
        /// </summary>
        public static string MessageCase_ForgotPasswordEmailSent {
            get {
                return ResourceManager.GetString("MessageCase_ForgotPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to user - user cancel payment.
        /// </summary>
        public static string MessageCase_HuyBoThanhToan {
            get {
                return ResourceManager.GetString("MessageCase_HuyBoThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string PaymentMethod_Cash {
            get {
                return ResourceManager.GetString("PaymentMethod_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string PaymentMethod_CreditCard {
            get {
                return ResourceManager.GetString("PaymentMethod_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string PaymentStatus_ChuaThanhToan {
            get {
                return ResourceManager.GetString("PaymentStatus_ChuaThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string PaymentStatus_DaThanhToan {
            get {
                return ResourceManager.GetString("PaymentStatus_DaThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed.
        /// </summary>
        public static string PaymentStatus_ThanhToanKhongThanhCong {
            get {
                return ResourceManager.GetString("PaymentStatus_ThanhToanKhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ProductStatus_Active {
            get {
                return ResourceManager.GetString("ProductStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string ProductStatus_Inactive {
            get {
                return ResourceManager.GetString("ProductStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site settings.
        /// </summary>
        public static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage System Email Templates.
        /// </summary>
        public static string SystemEmailTemplates {
            get {
                return ResourceManager.GetString("SystemEmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to admin - forgot password.
        /// </summary>
        public static string SystemEmailTemplateType_BackEndForgotPassword {
            get {
                return ResourceManager.GetString("SystemEmailTemplateType_BackEndForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to user - account created.
        /// </summary>
        public static string SystemEmailTemplateType_ConfirmNewAccountToUser {
            get {
                return ResourceManager.GetString("SystemEmailTemplateType_ConfirmNewAccountToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to user - confirm external id.
        /// </summary>
        public static string SystemEmailTemplateType_ExternalLoginIdConfirm {
            get {
                return ResourceManager.GetString("SystemEmailTemplateType_ExternalLoginIdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to admin - has new order.
        /// </summary>
        public static string SystemEmailTemplateType_HasNewOrder {
            get {
                return ResourceManager.GetString("SystemEmailTemplateType_HasNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify to admin - contact us.
        /// </summary>
        public static string SystemEmailTemplateType_StoreFrontContactUs {
            get {
                return ResourceManager.GetString("SystemEmailTemplateType_StoreFrontContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string WeekDay_Friday {
            get {
                return ResourceManager.GetString("WeekDay_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string WeekDay_Monday {
            get {
                return ResourceManager.GetString("WeekDay_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string WeekDay_Saturday {
            get {
                return ResourceManager.GetString("WeekDay_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string WeekDay_Sunday {
            get {
                return ResourceManager.GetString("WeekDay_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string WeekDay_Thursday {
            get {
                return ResourceManager.GetString("WeekDay_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string WeekDay_Tuesday {
            get {
                return ResourceManager.GetString("WeekDay_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string WeekDay_Wednesday {
            get {
                return ResourceManager.GetString("WeekDay_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
