//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Messages.BeScreens.CategoryRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Messages.BeScreens.CategoryRes.CategoryRes", typeof(CategoryRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new age.
        /// </summary>
        public static string AddNewAge {
            get {
                return ResourceManager.GetString("AddNewAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new image.
        /// </summary>
        public static string AddNewImage {
            get {
                return ResourceManager.GetString("AddNewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new lead time.
        /// </summary>
        public static string AddNewLeadTime {
            get {
                return ResourceManager.GetString("AddNewLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new number of chair.
        /// </summary>
        public static string AddNewNumberOfChair {
            get {
                return ResourceManager.GetString("AddNewNumberOfChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new number of dentist.
        /// </summary>
        public static string AddNewNumberOfDoctor {
            get {
                return ResourceManager.GetString("AddNewNumberOfDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new number of staff.
        /// </summary>
        public static string AddNewNumberOfStaff {
            get {
                return ResourceManager.GetString("AddNewNumberOfStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new position.
        /// </summary>
        public static string AddNewPosition {
            get {
                return ResourceManager.GetString("AddNewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new specialization.
        /// </summary>
        public static string AddNewSpecialization {
            get {
                return ResourceManager.GetString("AddNewSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new unit.
        /// </summary>
        public static string AddNewUOM {
            get {
                return ResourceManager.GetString("AddNewUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new using RC.
        /// </summary>
        public static string AddNewUsingRC {
            get {
                return ResourceManager.GetString("AddNewUsingRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artice.
        /// </summary>
        public static string Artice {
            get {
                return ResourceManager.GetString("Artice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy options.
        /// </summary>
        public static string BuyOptions {
            get {
                return ResourceManager.GetString("BuyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category list of .
        /// </summary>
        public static string CategoryListOf {
            get {
                return ResourceManager.GetString("CategoryListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code field is required.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories.
        /// </summary>
        public static string DanhMucLoaiSanPham {
            get {
                return ResourceManager.GetString("DanhMucLoaiSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display in home page.
        /// </summary>
        public static string DisplayInHomePage {
            get {
                return ResourceManager.GetString("DisplayInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit age.
        /// </summary>
        public static string EditAge {
            get {
                return ResourceManager.GetString("EditAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit lead time.
        /// </summary>
        public static string EditLeadTime {
            get {
                return ResourceManager.GetString("EditLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit number of chair.
        /// </summary>
        public static string EditNumberOfChair {
            get {
                return ResourceManager.GetString("EditNumberOfChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit number of dentist.
        /// </summary>
        public static string EditNumberOfDoctor {
            get {
                return ResourceManager.GetString("EditNumberOfDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit number of staff.
        /// </summary>
        public static string EditNumberOfStaff {
            get {
                return ResourceManager.GetString("EditNumberOfStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit position.
        /// </summary>
        public static string EditPosition {
            get {
                return ResourceManager.GetString("EditPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit specialization.
        /// </summary>
        public static string EditSpecialization {
            get {
                return ResourceManager.GetString("EditSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit unit.
        /// </summary>
        public static string EditUOM {
            get {
                return ResourceManager.GetString("EditUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit using RC.
        /// </summary>
        public static string EditUsingRC {
            get {
                return ResourceManager.GetString("EditUsingRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image list of.
        /// </summary>
        public static string ImageListOf {
            get {
                return ResourceManager.GetString("ImageListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image slide.
        /// </summary>
        public static string ImageSlide {
            get {
                return ResourceManager.GetString("ImageSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string KindOfProduct {
            get {
                return ResourceManager.GetString("KindOfProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu image.
        /// </summary>
        public static string MenuImage {
            get {
                return ResourceManager.GetString("MenuImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameOnly {
            get {
                return ResourceManager.GetString("NameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need buy.
        /// </summary>
        public static string NeedBuy {
            get {
                return ResourceManager.GetString("NeedBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need rent.
        /// </summary>
        public static string NeedRent {
            get {
                return ResourceManager.GetString("NeedRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Products.
        /// </summary>
        public static string SoSanPham {
            get {
                return ResourceManager.GetString("SoSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order.
        /// </summary>
        public static string Stt {
            get {
                return ResourceManager.GetString("Stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub menu style.
        /// </summary>
        public static string SubMenuStyle {
            get {
                return ResourceManager.GetString("SubMenuStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
    }
}
