//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Messages.BeScreens.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Messages.BeScreens.Menu.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval pending.
        /// </summary>
        public static string ApprovalPending {
            get {
                return ResourceManager.GetString("ApprovalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string BackendUsers {
            get {
                return ResourceManager.GetString("BackendUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank book report.
        /// </summary>
        public static string BankBookReport {
            get {
                return ResourceManager.GetString("BankBookReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash book report.
        /// </summary>
        public static string CashBookReport {
            get {
                return ResourceManager.GetString("CashBookReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash payment journal report.
        /// </summary>
        public static string CashPaymentJournalReport {
            get {
                return ResourceManager.GetString("CashPaymentJournalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash receipt journal report.
        /// </summary>
        public static string CashReceiptJournalReport {
            get {
                return ResourceManager.GetString("CashReceiptJournalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitors.
        /// </summary>
        public static string Competitors {
            get {
                return ResourceManager.GetString("Competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string CurrentCustomers {
            get {
                return ResourceManager.GetString("CurrentCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer service.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string DanhSachNhomSanPham {
            get {
                return ResourceManager.GetString("DanhSachNhomSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data settings.
        /// </summary>
        public static string DataSettings {
            get {
                return ResourceManager.GetString("DataSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealers.
        /// </summary>
        public static string Dealers {
            get {
                return ResourceManager.GetString("Dealers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt receivable detail report.
        /// </summary>
        public static string DebtReceivableDetailReport {
            get {
                return ResourceManager.GetString("DebtReceivableDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt receivable summary report.
        /// </summary>
        public static string DebtReceivableSummaryReport {
            get {
                return ResourceManager.GetString("DebtReceivableSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Templates.
        /// </summary>
        public static string EmailTemplate {
            get {
                return ResourceManager.GetString("EmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose mail.
        /// </summary>
        public static string GuiMail {
            get {
                return ResourceManager.GetString("GuiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Slide.
        /// </summary>
        public static string ImageSlide {
            get {
                return ResourceManager.GetString("ImageSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item sale journal.
        /// </summary>
        public static string ItemSaleJournal {
            get {
                return ResourceManager.GetString("ItemSaleJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead time.
        /// </summary>
        public static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Image.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages on Site Setup.
        /// </summary>
        public static string MessageSetup {
            get {
                return ResourceManager.GetString("MessageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product categories.
        /// </summary>
        public static string NhomSanPham {
            get {
                return ResourceManager.GetString("NhomSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of chair.
        /// </summary>
        public static string NumberOfChair {
            get {
                return ResourceManager.GetString("NumberOfChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dentist.
        /// </summary>
        public static string NumberOfDoctor {
            get {
                return ResourceManager.GetString("NumberOfDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of staff.
        /// </summary>
        public static string NumberOfStaff {
            get {
                return ResourceManager.GetString("NumberOfStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential customers.
        /// </summary>
        public static string PotentialCustomers {
            get {
                return ResourceManager.GetString("PotentialCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device (Products).
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospects customers.
        /// </summary>
        public static string ProspectsCustomers {
            get {
                return ResourceManager.GetString("ProspectsCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale by customer report.
        /// </summary>
        public static string SaleByCustomerReport {
            get {
                return ResourceManager.GetString("SaleByCustomerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale by employee report.
        /// </summary>
        public static string SaleByEmployeeReport {
            get {
                return ResourceManager.GetString("SaleByEmployeeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale by product report.
        /// </summary>
        public static string SaleByProductReport {
            get {
                return ResourceManager.GetString("SaleByProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service report.
        /// </summary>
        public static string ServiceReport {
            get {
                return ResourceManager.GetString("ServiceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string StoreFrontAboutUsPageSetup {
            get {
                return ResourceManager.GetString("StoreFrontAboutUsPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string StoreFrontContactUsPageSetup {
            get {
                return ResourceManager.GetString("StoreFrontContactUsPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string StoreFrontHelpPageSetup {
            get {
                return ResourceManager.GetString("StoreFrontHelpPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string StoreFrontHomePageSetup {
            get {
                return ResourceManager.GetString("StoreFrontHomePageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string StoreFrontPhotosPageSetup {
            get {
                return ResourceManager.GetString("StoreFrontPhotosPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string StoreFrontPrivacyPageSetup {
            get {
                return ResourceManager.GetString("StoreFrontPrivacyPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Front Setup.
        /// </summary>
        public static string StoreFrontSetup {
            get {
                return ResourceManager.GetString("StoreFrontSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of use.
        /// </summary>
        public static string StoreFrontTermOfUsePageSetup {
            get {
                return ResourceManager.GetString("StoreFrontTermOfUsePageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using RC.
        /// </summary>
        public static string UsingRC {
            get {
                return ResourceManager.GetString("UsingRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
