//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Messages.BeScreens.CustomerRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Messages.BeScreens.CustomerRes.CustomerRes", typeof(CustomerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add customer marker.
        /// </summary>
        public static string AddCustomerMarker {
            get {
                return ResourceManager.GetString("AddCustomerMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new customer.
        /// </summary>
        public static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new potential customer.
        /// </summary>
        public static string AddNewPotentialCustomer {
            get {
                return ResourceManager.GetString("AddNewPotentialCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new prospects customer.
        /// </summary>
        public static string AddNewProspectsCustomer {
            get {
                return ResourceManager.GetString("AddNewProspectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new visit.
        /// </summary>
        public static string AddNewVisit {
            get {
                return ResourceManager.GetString("AddNewVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not geolocate your address.
        /// </summary>
        public static string AddressCanNotFind {
            get {
                return ResourceManager.GetString("AddressCanNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address is required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to.
        /// </summary>
        public static string AssignTo {
            get {
                return ResourceManager.GetString("AssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shop name is required.
        /// </summary>
        public static string BranchNameRequired {
            get {
                return ResourceManager.GetString("BranchNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find direction from company to customer.
        /// </summary>
        public static string CanNotFindRoute {
            get {
                return ResourceManager.GetString("CanNotFindRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load direction. Please set company address and input customer address or set customer location on map..
        /// </summary>
        public static string CanNotLoadDirection {
            get {
                return ResourceManager.GetString("CanNotLoadDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cell phone filed is required.
        /// </summary>
        public static string CellPhoneRequired {
            get {
                return ResourceManager.GetString("CellPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change type.
        /// </summary>
        public static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change type for customer.
        /// </summary>
        public static string ChangeTypeForCustomer {
            get {
                return ResourceManager.GetString("ChangeTypeForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/ Provine.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city field is required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Id.
        /// </summary>
        public static string ClinicId {
            get {
                return ResourceManager.GetString("ClinicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clinic id field is required.
        /// </summary>
        public static string ClinicIdRequired {
            get {
                return ResourceManager.GetString("ClinicIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic information.
        /// </summary>
        public static string ClinicInformation {
            get {
                return ResourceManager.GetString("ClinicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic name.
        /// </summary>
        public static string ClinicName {
            get {
                return ResourceManager.GetString("ClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clinic name field is required.
        /// </summary>
        public static string ClinicNameRequired {
            get {
                return ResourceManager.GetString("ClinicNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic phone.
        /// </summary>
        public static string ClinicPhone {
            get {
                return ResourceManager.GetString("ClinicPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmPasswordNew {
            get {
                return ResourceManager.GetString("ConfirmPasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer type is required.
        /// </summary>
        public static string CustomerTypeRequired {
            get {
                return ResourceManager.GetString("CustomerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is invalid.
        /// </summary>
        public static string DateVisitInvalid {
            get {
                return ResourceManager.GetString("DateVisitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date field is required.
        /// </summary>
        public static string DateVisitRequired {
            get {
                return ResourceManager.GetString("DateVisitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DentistEmail {
            get {
                return ResourceManager.GetString("DentistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist information.
        /// </summary>
        public static string DentistInfo {
            get {
                return ResourceManager.GetString("DentistInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist name.
        /// </summary>
        public static string DentistName {
            get {
                return ResourceManager.GetString("DentistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dentist name is required.
        /// </summary>
        public static string DentistNameRequired {
            get {
                return ResourceManager.GetString("DentistNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string DentistPhone {
            get {
                return ResourceManager.GetString("DentistPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The district field is required.
        /// </summary>
        public static string DistrictRequired {
            get {
                return ResourceManager.GetString("DistrictRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit potential customer.
        /// </summary>
        public static string EditPotentialCustomer {
            get {
                return ResourceManager.GetString("EditPotentialCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit prospects customer.
        /// </summary>
        public static string EditProspectsCustomer {
            get {
                return ResourceManager.GetString("EditProspectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit customer info.
        /// </summary>
        public static string EditUserPageTitle {
            get {
                return ResourceManager.GetString("EditUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit visit.
        /// </summary>
        public static string EditVisit {
            get {
                return ResourceManager.GetString("EditVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already existed in the system.
        /// </summary>
        public static string EmailExisted {
            get {
                return ResourceManager.GetString("EmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid format.
        /// </summary>
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Row {0}) Clinic Id is required.
        /// </summary>
        public static string ExcelClinicIdRequired {
            get {
                return ResourceManager.GetString("ExcelClinicIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Row {0}) Clinic Name is required.
        /// </summary>
        public static string ExcelClinicNameRequired {
            get {
                return ResourceManager.GetString("ExcelClinicNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Row {0}) Email is not valid format : &quot;{1}&quot;.
        /// </summary>
        public static string ExcelEmailInvalid {
            get {
                return ResourceManager.GetString("ExcelEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name field is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name field is required.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History purchase.
        /// </summary>
        public static string HistoryPurchase {
            get {
                return ResourceManager.GetString("HistoryPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not choose image.
        /// </summary>
        public static string ImageIsRequired {
            get {
                return ResourceManager.GetString("ImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image list of customer.
        /// </summary>
        public static string ImageListOf {
            get {
                return ResourceManager.GetString("ImageListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting device.
        /// </summary>
        public static string InterestingDevice {
            get {
                return ResourceManager.GetString("InterestingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined date.
        /// </summary>
        public static string JoinedDate {
            get {
                return ResourceManager.GetString("JoinedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join seminar.
        /// </summary>
        public static string JoinSeminar {
            get {
                return ResourceManager.GetString("JoinSeminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name field is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead time.
        /// </summary>
        public static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least 1 customer to delete.
        /// </summary>
        public static string MustSelectAtLeast1CustomerToDelete {
            get {
                return ResourceManager.GetString("MustSelectAtLeast1CustomerToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of chair.
        /// </summary>
        public static string NumberOfChair {
            get {
                return ResourceManager.GetString("NumberOfChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dentist.
        /// </summary>
        public static string NumberOfDentist {
            get {
                return ResourceManager.GetString("NumberOfDentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of staff.
        /// </summary>
        public static string NumberOfStaff {
            get {
                return ResourceManager.GetString("NumberOfStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer list.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promise.
        /// </summary>
        public static string Promise {
            get {
                return ResourceManager.GetString("Promise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provine.
        /// </summary>
        public static string Provine {
            get {
                return ResourceManager.GetString("Provine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Provine is required.
        /// </summary>
        public static string ProvineRequired {
            get {
                return ResourceManager.GetString("ProvineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop homepage layout.
        /// </summary>
        public static string ShopHomePageLayout {
            get {
                return ResourceManager.GetString("ShopHomePageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Status.
        /// </summary>
        public static string ShopStatus {
            get {
                return ResourceManager.GetString("ShopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff field is required.
        /// </summary>
        public static string StaffRequired {
            get {
                return ResourceManager.GetString("StaffRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer info.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string UserOnly {
            get {
                return ResourceManager.GetString("UserOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using device.
        /// </summary>
        public static string UsingDevice {
            get {
                return ResourceManager.GetString("UsingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using RC.
        /// </summary>
        public static string UsingRC {
            get {
                return ResourceManager.GetString("UsingRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit from.
        /// </summary>
        public static string VisitFrom {
            get {
                return ResourceManager.GetString("VisitFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit to.
        /// </summary>
        public static string VisitTo {
            get {
                return ResourceManager.GetString("VisitTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must be smaller than end time.
        /// </summary>
        public static string WorkingHourInvalid {
            get {
                return ResourceManager.GetString("WorkingHourInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not input {0} time for {1}.
        /// </summary>
        public static string WorkingHourRequired {
            get {
                return ResourceManager.GetString("WorkingHourRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
    }
}
