//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Messages.ServiceMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Messages.ServiceMessage.ServiceMessage", typeof(ServiceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is pendding for approval.
        /// </summary>
        public static string AccountPendingApproval {
            get {
                return ResourceManager.GetString("AccountPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not find your request data in the system. Please contact administrator.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add new item into this group. This group has child groups..
        /// </summary>
        public static string CannotAddNewIntoThisGroup {
            get {
                return ResourceManager.GetString("CannotAddNewIntoThisGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find email or phone.
        /// </summary>
        public static string CanNotFindEmailOrPhone {
            get {
                return ResourceManager.GetString("CanNotFindEmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is used, can not delete. Please delete all product belong to this category and then  you can delete this category..
        /// </summary>
        public static string CategoryIsUsedCanNotDelete {
            get {
                return ResourceManager.GetString("CategoryIsUsedCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category is refered in project list.Can not delete..
        /// </summary>
        public static string CategoryIsUsedInProjectsCanNotDelete {
            get {
                return ResourceManager.GetString("CategoryIsUsedInProjectsCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clinic id is already existed.
        /// </summary>
        public static string ClinicIdExisted {
            get {
                return ResourceManager.GetString("ClinicIdExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is already existed in the system.
        /// </summary>
        public static string CodeExisted {
            get {
                return ResourceManager.GetString("CodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit card expiration date field is required.
        /// </summary>
        public static string CreditCardExpDateIsRequired {
            get {
                return ResourceManager.GetString("CreditCardExpDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Expire Date is invalid.
        /// </summary>
        public static string CreditCardExpireDateIsInvalid {
            get {
                return ResourceManager.GetString("CreditCardExpireDateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rider have not any credit card.
        /// </summary>
        public static string CreditCardNotFound {
            get {
                return ResourceManager.GetString("CreditCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number Is Existed. Can not add new or update.
        /// </summary>
        public static string CreditCardNumberIsExisted {
            get {
                return ResourceManager.GetString("CreditCardNumberIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number is invalid.
        /// </summary>
        public static string CreditCardNumberIsInvalid {
            get {
                return ResourceManager.GetString("CreditCardNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Credit Card Number field is required.
        /// </summary>
        public static string CreditCardNumberIsRequired {
            get {
                return ResourceManager.GetString("CreditCardNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CVV field is required.
        /// </summary>
        public static string CVVIsRequired {
            get {
                return ResourceManager.GetString("CVVIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is invalid.
        /// </summary>
        public static string DataIsInvalid {
            get {
                return ResourceManager.GetString("DataIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance is invalid.
        /// </summary>
        public static string DistanceInvalid {
            get {
                return ResourceManager.GetString("DistanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already existed in the system.
        /// </summary>
        public static string EmailExisted {
            get {
                return ResourceManager.GetString("EmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address is invalid.
        /// </summary>
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address notification is not setup.
        /// </summary>
        public static string EmailNotificationIsNotSetup {
            get {
                return ResourceManager.GetString("EmailNotificationIsNotSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template data not found.
        /// </summary>
        public static string EmailTemplateDataNotFound {
            get {
                return ResourceManager.GetString("EmailTemplateDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Row {0}) Clinic id &quot;{1}&quot; is already existed.
        /// </summary>
        public static string ExcelFileClinicIdExisted {
            get {
                return ResourceManager.GetString("ExcelFileClinicIdExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File&apos;s size maximum is 5MB.
        /// </summary>
        public static string FileMaxSize5MB {
            get {
                return ResourceManager.GetString("FileMaxSize5MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Name is required.
        /// </summary>
        public static string FileNameRequired {
            get {
                return ResourceManager.GetString("FileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of file is not valid.
        /// </summary>
        public static string FileTypeIsInvalid {
            get {
                return ResourceManager.GetString("FileTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field is required.
        /// </summary>
        public static string FirstNameIsRequired {
            get {
                return ResourceManager.GetString("FirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of image is empty.
        /// </summary>
        public static string ImageDataIsEmpty {
            get {
                return ResourceManager.GetString("ImageDataIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of image is not base 64 string.
        /// </summary>
        public static string ImageDataIsNotBase64String {
            get {
                return ResourceManager.GetString("ImageDataIsNotBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field is required.
        /// </summary>
        public static string LastNameIsRequired {
            get {
                return ResourceManager.GetString("LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has been sent.
        /// </summary>
        public static string MessageHasBeenSent {
            get {
                return ResourceManager.GetString("MessageHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already existed.
        /// </summary>
        public static string NameIsExisted {
            get {
                return ResourceManager.GetString("NameIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data effect.
        /// </summary>
        public static string NoDataEffect {
            get {
                return ResourceManager.GetString("NoDataEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is using by order, delete order first..
        /// </summary>
        public static string OrderStatusIsUsingByOrderCannotDelete {
            get {
                return ResourceManager.GetString("OrderStatusIsUsingByOrderCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method is invalid.
        /// </summary>
        public static string PaymentMethodIsInvalid {
            get {
                return ResourceManager.GetString("PaymentMethodIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is registered in the system.
        /// </summary>
        public static string PhoneIsExisted {
            get {
                return ResourceManager.GetString("PhoneIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone field is required.
        /// </summary>
        public static string PhoneIsRequired {
            get {
                return ResourceManager.GetString("PhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        public static string PhoneNumberIsInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password.
        /// </summary>
        public static string PleaseInputPassword {
            get {
                return ResourceManager.GetString("PleaseInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Language is invalid.
        /// </summary>
        public static string PreferLanguageIsInvalid {
            get {
                return ResourceManager.GetString("PreferLanguageIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Prefer Language field is required.
        /// </summary>
        public static string PreferLanguageRequired {
            get {
                return ResourceManager.GetString("PreferLanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product option is used by categories or product order, can not delete!.
        /// </summary>
        public static string ProductOptionIsUsedCanNotDelete {
            get {
                return ResourceManager.GetString("ProductOptionIsUsedCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromoCode Is Existed. Please try again..
        /// </summary>
        public static string PromoCodeIsExisted {
            get {
                return ResourceManager.GetString("PromoCodeIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect.
        /// </summary>
        public static string PwdIncorrect {
            get {
                return ResourceManager.GetString("PwdIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is assigned for users. Can not delete.
        /// </summary>
        public static string RoleIsUsed {
            get {
                return ResourceManager.GetString("RoleIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data successfull.
        /// </summary>
        public static string SaveDataSuccessMessage {
            get {
                return ResourceManager.GetString("SaveDataSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up successfull. Please login.
        /// </summary>
        public static string SignUpSuccessMessage {
            get {
                return ResourceManager.GetString("SignUpSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string length is excess maximun.
        /// </summary>
        public static string StringLenghtIsInvalid {
            get {
                return ResourceManager.GetString("StringLenghtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone is invalid.
        /// </summary>
        public static string TimeZoneIsInvalid {
            get {
                return ResourceManager.GetString("TimeZoneIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable find this user.
        /// </summary>
        public static string UnableFindUser {
            get {
                return ResourceManager.GetString("UnableFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image successfull.
        /// </summary>
        public static string UploadImageSuccessfull {
            get {
                return ResourceManager.GetString("UploadImageSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is current locked.
        /// </summary>
        public static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name can not have white space.
        /// </summary>
        public static string UserNameCanNotHaveWhiteSpace {
            get {
                return ResourceManager.GetString("UserNameCanNotHaveWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user name is already existed in the system.
        /// </summary>
        public static string UserNameExisted {
            get {
                return ResourceManager.GetString("UserNameExisted", resourceCulture);
            }
        }
    }
}
